#!/usr/bin/env python3
"""Generate src/img_wave.c — pixelated Great Wave off Kanagawa (Hokusai,
1831, public domain) for the standby dashboard's left band.

Pipeline: Wikimedia scan -> left-portrait crop of the crest -> 75x105 ->
autocontrast -> hard threshold (the woodblock's flat colors dither badly but
threshold beautifully) -> 2x nearest upscale to 150x210 for the chunky
"pixel art" look -> LVGL LV_IMG_CF_INDEXED_1BIT C array (~4 KB).

Usage: python3 tools/make_wave.py  (writes src/img_wave.c; caches the scan
in ~/.cache/express-ghalib/)
"""
import os
import hashlib
import subprocess
import sys

from PIL import Image, ImageOps

URL = ("https://commons.wikimedia.org/wiki/Special:FilePath/"
       "Tsunami_by_hokusai_19th_century.jpg")
CACHE = os.path.expanduser("~/.cache/express-ghalib/wave.jpg")
OUT = os.path.join(os.path.dirname(__file__), "..", "src", "img_wave.c")

# Checksum of the source image this artwork was generated from. Wikimedia can
# re-derive a file at the same path; pinning the digest keeps the dither
# reproducible and catches a substituted download.
SHA256 = "30c170260de393f51bd592adacc6f0714b60f157c09744e9c5b6d46e6a613718"


def verify(path, expected):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    if h.hexdigest() != expected:
        sys.exit(f"checksum mismatch for {path}\n"
                 f"  expected {expected}\n  got      {h.hexdigest()}\n"
                 f"Delete the file to re-download.")


SMALL = (75, 105)     # dither/threshold resolution
SCALE = 2             # nearest-neighbour upscale factor
THRESH = 122

def main():
    if not os.path.exists(CACHE):
        os.makedirs(os.path.dirname(CACHE), exist_ok=True)
        subprocess.run(["curl", "-fL", "-o", CACHE + ".part", URL], check=True)
        os.rename(CACHE + ".part", CACHE)
    verify(CACHE, SHA256)

    im = Image.open(CACHE).convert("L")
    W, H = im.size
    crop = im.crop((int(0.08 * W), int(0.02 * H), int(0.55 * W),
                    int(0.94 * H)))
    crop = ImageOps.autocontrast(crop.resize(SMALL, Image.LANCZOS))
    bw = crop.point(lambda v: 255 if v > THRESH else 0, "1")
    bw = bw.resize((SMALL[0] * SCALE, SMALL[1] * SCALE), Image.NEAREST)

    w, h = bw.size
    px = bw.load()
    stride = (w + 7) // 8
    # palette (2 x lv_color32_t, byte order B,G,R,A): [0]=white, [1]=black
    data = bytearray([0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0xFF])
    for y in range(h):
        row = bytearray(stride)
        for x in range(w):
            if px[x, y] == 0:  # dark pixel -> palette index 1
                row[x // 8] |= 0x80 >> (x % 8)
        data += row

    with open(OUT, "w") as f:
        f.write("/* Generated by tools/make_wave.py — The Great Wave off\n"
                " * Kanagawa (Hokusai, 1831, public domain), %dx%d 1-bit for\n"
                " * the standby dashboard. Do not edit by hand. */\n"
                "#include \"lvgl.h\"\n\n"
                "static const uint8_t img_wave_map[] = {\n" % (w, h))
        for i in range(0, len(data), 16):
            f.write("  " + ",".join("0x%02X" % b for b in data[i:i + 16]) +
                    ",\n")
        f.write("};\n\n"
                "const lv_img_dsc_t img_wave = {\n"
                "  .header.cf = LV_IMG_CF_INDEXED_1BIT,\n"
                "  .header.always_zero = 0,\n"
                "  .header.reserved = 0,\n"
                "  .header.w = %d,\n"
                "  .header.h = %d,\n"
                "  .data_size = sizeof(img_wave_map),\n"
                "  .data = img_wave_map,\n"
                "};\n" % (w, h))
    print("wrote %s (%d bytes, %dx%d)" % (OUT, len(data), w, h))

if __name__ == "__main__":
    main()
